<?php

namespace AppBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function returnGroups($category){
        $em = $this->getEntityManager();
        $groups = $em->createQuery
        ('SELECT g FROM UserStoriesBundle:Groups AS g LEFT JOIN UserStoriesBundle:User AS u
                       WITH g.id = u.groups.id WHERE u.id=:id')->setParameter(':id', $id)->getResult();
        ('SELECT a FROM AppBundle:Advert AS a LEFT JOIN AppBundle:Category AS c
                       WITH a.id = c.id WHERE c.id=:id')->setParameter(':id', $id)->getResult();

        return $groups;
    }

}
